app:
  helpers:
    user:
      size: 80
  models:
    user:
      name: 50
      email: 255
      pass: 6
users:
  user:
    size: 50
sessions:
  number: "1"
  not_found: "not found user"
per_page:
  user: 20
production:
  host: "<your heroku app>.herokuapp.com"
  address: "smtp.sendgrid.net"
  port: "587"
  domain: "heroku.com"
