app:
  helpers:
    user:
      size: 80
  models:
    user:
      name: 50
      email: 255
      pass: 6
      time: 2
users:
  user:
    size: 50
number: "1"
sessions:
  not_found: "not found user"
per_page:
  user: 20
production:
  host: "<your heroku app>.herokuapp.com"
  address: "smtp.sendgrid.net"
  port: "587"
  domain: "heroku.com"
micropost:
  size: 50
  maximum: 140
  picture_size: 5
avatar:
  size: 30
